### ISSUE TITLE
Setup and configuration for crawler

### ISSUE THREAD

**Issue by cnvo** [wholenews/wholenews#2]
I've set up on another instance (awesome platform), I'm having some problems with the crawler.

Is there a sample configuration for the crawler that would be useful? 
And in what order should this be done?

Also would like to contact you further via email.

**Comment by wholenews** [comment]
Thanks for your interest. I wasn't expecting anyone to notice the repo. It will take some work to get a second instance running:

- Replace all hardcoded bucket names (e.g. grep -r "gs://" packages/*/src/*) with environment variables.
- Update terraform deploy to do everything needed
- Update crawler configuration to not expect missing classifier models.  
- Create deploy script that runs terraform (which populates secrets), deploys addLink, crawl, cluster, archive, cloud functions, and deploys server and ui to app engine. 
- Add/automate adding scrapers, e.g. http://whole.news/scraper/news
- If everything works then you can add feeds in the UI.

Good luck!  You're welcome to send your email or join the wholenews Slack.

**Comment by cnvo** [comment]
> Good luck! You're welcome to send your email or join the wholenews Slack.

Sure I'd like an invite: trevor@engineer.com
